### ISSUE TITLE
Unable to use evaporate.js in a web worker

### ISSUE THREAD

**Issue by m-andrew-albright** [TTLabs/EvaporateJS#308] opened 2017-02-05 16:45 UTC
Due to the way evaporate.js parses a url into a uri object (see https://github.com/TTLabs/EvaporateJS/blob/master/evaporate.js#L1981) by using `document.createElement('a');`, it cannot currently be used in a web worker without some modifications (such as pulling in jsdom, which I have not yet tried so I can't guarantee it works).

Currently, we are using AWS Signature V2, and calculating the MD5 on large file uploads causes our UI to stutter and stop responding until the uploading is finished; this is the reason we are trying to use evaporate.js in a web worker in the first place, so if there is some workaround to this performance issue, I would greatly welcome any recommendations.

Thanks for the awesome library!

**Comment by bikeath1337** [comment] 2017-02-06 12:28
That makes send @m-andrew-albright but what I still don't understand is why your client is blocking when creating the checksum. I've not seen any delays with part sizes of 15MB or less. What is your part size?

I'm open to other solutions for parsing a URL. Using `document.createElement` seemed like a safe, reliable option.

**Comment by m-andrew-albright** [comment] 2017-02-06 12:45
I believe we are using the default; which is `6 * 1024 * 1024`.

Now I'm not so sure that this is the problem, because I was able to successfully modify evaporate to allow asynchronous md5 generation, which I delegated to a web worker, but my app still becomes very unresponsive and jittery while uploading.

I've only been doing front end dev for about eight months, and I still have a difficult time understanding the cpu profiler in chrome's devtools, but it seemed to me that the MD5 calculation was the culprit:

![image](https://cloud.githubusercontent.com/assets/4950445/22647511/85815aba-ec37-11e6-92cf-93523d7832b5.png)


^ This is prior to my attempt to make the MD5 asynchronous and delegated into a web worker, and this is after:

![image](https://cloud.githubusercontent.com/assets/4950445/22647497/76ebca08-ec37-11e6-82a1-cee8cd07db72.png)

It's my understanding that (program) is native code running, and if the jittering/unresponsiveness is due to _that_, it may be difficult or impossible to pinpoint exactly what is causing this.

Thanks for responding!

**Comment by bikeath1337** [comment] 2017-02-06 12:55
Thank you. FWIW, Evaporate calls the MD5 method asynchronously already: a) when fetching the part bytes to digest b) through the Promise method that creates the digest.

Why don't you just diff two times in your MD5 method and verify for sure?

**Comment by m-andrew-albright** [comment] 2017-02-06 13:13
By "asynchronous" I really meant to say "in another thread" which - the only way to do that in client JS is by using web workers.  It really _seems_ like the application's unresponsiveness corresponds to the timings of calculating the MD5, and that is one of the most CPU-intensive things happening during these file uploads.  However, getting the MD5 to be calculating in the web worker didn't seem to have any impact on these issues we're having.

I'm not sure what you mean by "diff" two times in my MD5 method; the only "diff" I'm familiar with is diffing two files for changes.

Thanks for taking the time to discuss this with me.

**Comment by bikeath1337** [comment] 2017-02-06 13:26
No problem. By "diff" i meant, take calculate the delta of the start time and end time within the method to verify the approximate time cost to create the digest.

**Comment by m-andrew-albright** [comment] 2017-02-06 13:30
Ah yes, I did that prior to moving the MD5 into a web worker, and with AWS-SDK, it was something like 500ms per call; with SparkMD5, it's consistently 160ms.  I will try calculating within the web worker and let you know what that looks like (if I understand correctly, I would use console.time() in the web worker before and after the MD5 function call)

**Comment by bikeath1337** [comment] 2017-02-10 11:38
#312 proposes a small change to how the aws_url is parsed. Would this be an improvement for compatibility with node for you?

**Comment by m-andrew-albright** [comment] 2017-02-10 17:15
That looks like it might help - I can't tell if URL is available in web workers though:

**Comment by YMIndustries** [comment] 2017-02-16 22:07
Hi,

I'm running EvaporateJS in a WebWorker too. I got it working without modifications by using a few shims and NPM packages.

```
var window = self; // For Worker-unaware scripts

// Shim to make Evaporate work in a Worker
var document = {
	createElement: function() {
		var href = undefined;
		
		var elm = {
			set href(url) {
				var obj = new URL(url);
				elm.protocol = obj.protocol;
				elm.hostname = obj.hostname;
				elm.pathname = obj.pathname;
				elm.port = obj.port;
				elm.search = obj.search;
				elm.hash = obj.hash;
				elm.host = obj.host;
				href = url;
			},
			get href() {
				return href;
			},
			protocol: undefined,
			hostname: undefined,
			pathname: undefined,
			port: undefined,
			search: undefined,
			hash: undefined,
			host: undefined
		};
		
		return elm;
	}
};

importScripts("/lib/sha256/sha256.min.js");
importScripts("/lib/spark-md5/spark-md5.min.js");
importScripts("/lib/url-parse/url-parse.js");
importScripts("/lib/xmldom/xmldom.js");
importScripts("/lib/evaporate/evaporate.js");

DOMParser = self.xmldom.DOMParser;
```

xmldom and url-parse can be found on NPM and work in the browser after they've been Browserify'd. The easiest way to do this is to fetch them from wzrd.in (essentially Browserify-as-a-service):

https://wzrd.in/standalone/url-parse@latest

https://wzrd.in/standalone/xmldom@latest

I'm still running into the issue where the Worker is somehow blocking the main thread, but I only experience it in Chrome. Edge and Firefox don't have this problem. I made a [StackOverflow post](http://stackoverflow.com/questions/41604594/worker-blocking-ui-thread-in-chrome) about it but haven't received any useful responses.

**Comment by m-andrew-albright** [comment] 2017-02-16 22:17
@YMIndustries Thanks for chiming in; I actually came upon your SO post at one point in my journey to find the solution to this issue.

I have been pulled into other areas of our front end, but this bug is glaring at me from the top of the prioritized backlog, and I have no idea how to solve it if web workers don't do the trick.

**Comment by YMIndustries** [comment] 2017-02-16 22:31
@m-andrew-albright I'm in the exact same position. I'm working on more pressing things at the moment, but our app allows users to type descriptions and such while their upload is running in the background, and the freezes every couple of seconds make the user experience pretty dreadful. It also really frustrates me because according to my understanding of Web Workers and all the documentation I can find, the way I've written it Should Work (tm). I actually think this is a Chrome bug, but in order to report it as such I'd need to create a much simpler way of reproducing it that I could share. I think I'll have to do that at some point, but I don't have the time right now.

**Comment by bikeath1337** [comment] 2017-02-16 22:35
I don't see any performance glitches or hangs on any of my browsers: Chrome, Safari or Win 11 with a 6MB part size. Can you give me a test example I can try out locally (without web workers)? @m-andrew-albright

**Comment by bikeath1337** [comment] 2017-02-17 12:50
Sorry the momentary lack of understanding. I think I now understand that you're using web works to offload the entire upload process. For some silly reason I was focusing on running just the checksum calculation.

I'm happy to address compatibility with Evaporate in a web worker and now understand that part of this discussion might be a bug in web workers that makes it not cooperative on Chrome.

**Comment by m-andrew-albright** [comment] 2017-02-17 13:11
@bikeath1337 This is still on my backburner (but not off the stove) - as soon as I switch back over to trying to solve this issue, I will get you as much information as I can regarding our setup.

For now though, it's probably worth mentioning that we are using evaporate as part of a proprietary media system's client interface, and it is being used in an Aurelia SPA.  It's possible that something Aurelia is doing is degrading the performance of evaporatejs; again, I'll get you as much information as I can when I switch back over to trying to solve this.

@YMIndustries I don't suppose you're using Aurelia, are you?

**Comment by YMIndustries** [comment] 2017-02-17 14:12
@m-andrew-albright Nope, AngularJS here. I tried disabling all the places where my upload causes a digest cycle, but this had no effect. Seems to be the MD5 hashing that's causing the issue for me too.

I actually have a new hunch, which is that perhaps because the File object is created in the main thread, reading its contents from disk might also take place in the main thread? Not really sure how to get around this though.

**Comment by m-andrew-albright** [comment] 2017-02-18 18:07
@YMIndustries  That's a really good insight; I think you're onto something there.

**Comment by bikeath1337** [comment] 2017-03-05 19:04
The upcoming 2.0.9 removes dependencies on any DOM manipulation by either using Regex's to parse XML responses or by using the built-in URL class, if available.

**Comment by bikeath1337** [comment] 2017-03-14 20:39
I'm curious if anyone has found that 2.0.9 is friendlier to adapt to web workers? What else might need to be made more generic, if anyone knows?

**Comment by YMIndustries** [comment] 2017-03-16 22:18
Hi @bikeath1337, sorry for the delay in being able to test this. I really appreciate how active you are in resolving issues for even niche use cases and I'm sorry that I'm not always able to respond in a timely manner.

I've just updated my project to use 2.0.9 and in doing this I was also able to remove ALL of the shims I had in place to get EvaporateJS to run in a web worker. Previously I required 3 shims, for localStorage, URL manipulation and XML parsing.

My usage of EvaporateJS is rather simplistic, I don't use features such as allowS3ExistenceOptimization and I currently don't even support resuming uploads, but for the simple act of uploading a large file I can confirm that EvaporateJS now runs flawlessly in a Web Worker.

Thanks!

**Comment by m-andrew-albright** [comment] 2017-03-17 13:52
@YMIndustries So you are no longer experiencing the locking up when uploading large files?  What was your solution, to move the entirety of the uploading into a web worker?  I will be getting back to this bug this sprint, so it would be helpful to know the best angle to approach this.

**Comment by bikeath1337** [comment] 2017-03-17 20:08
I think that the message here was that the issue with the cost of md5 calculation is still an issue but otherwise Evaporate can run as-is in a web worker.

I believe that the cost of calculation Is something outside of the bounds of evaporate.

**Comment by YMIndustries** [comment] 2017-03-17 23:35
@m-andrew-albright Sorry for the confusion, I still experience the stuttering, I just no longer need any shims to prevent errors when doing the upload in a web worker. Perhaps I shouldn't have uses the word 'flawless'. Best of luck with the stuttering issue, please let me know if you solve it.

**Comment by m-andrew-albright** [comment] 2017-04-02 13:26
Ok, I finally am getting around to trying to solve the performance issues our app seems to have with using evaporate.js.

I disabled the md5 hashing, but the jankiness is still terrible.  I have some suspicions that the problem arises from aurelia hooking into the microTaskQueue, but maybe I'm off base here.  I'm including a screenshot from my performance timeline in chrome devtools:

![image](https://cloud.githubusercontent.com/assets/4950445/24587488/51d1e95c-177d-11e7-8fa6-51cb6192e54e.png)

I am only just learning how to use this profiling (awesome) tool set in chrome, so I may be missing some obvious things here, but to me it seems the UI is locking up due to whatever is happening inside of the "XHR Ready State Change" event, and that seems to be handled inside of a microTask.

Aurelia uses the microTask queue as a core part of how it works.  I'm not learned enough at this point to know for sure, but I'm _very_ suspicious that there is some negative interaction between aurelia and evaporate.js.

The scope of our performance problems are outside the scope of this issue probably - should I open a separate issue and close this one out?  It seems evaporate can run inside a web worker, according to some comments above.

**Comment by bikeath1337** [comment] 2017-04-05 18:42
@m-andrew-albright Thanks for the additional info. I assume your test use V2 signatures and no MD5. If so, then you should be certain to test against v2.1.0. This version cleared up a memory retention issue with blob uploads without MD5. 

As to your suspicion, it is hard for me to see that evaporate is the culprit here. All of evaporate's processing happens before the part is submitted; the only hook we have into `onreadystatechange` is for the completion of the request.

Otherwise, evaporate passes a blob to the XHR and leaves the implementation of the upload to the browser. Other than that, one theory (and only a theory!) might be that the available async "threads" is more limited in a worker and there are too many tasks to handle?

**Comment by m-andrew-albright** [comment] 2017-04-19 18:16
I was finally able to spend some time working on this.

I successfully got evaporate running in a web worker, but unfortunately it did not solve the jank issue we are having.

**Comment by bikeath1337** [comment] 2017-04-19 21:14
Did you have to make any changes to EvaporateJS to get it to work in the web worker? I'd just like to confirm that the latest version is compatible in all other aspects. Thanks for the reply!

**Comment by m-andrew-albright** [comment] 2017-04-19 23:05
No changes were necessary for evaporate to run in a web worker.  👍

**Comment by bikeath1337** [comment] 2017-05-05 10:44
Closing this ticket as you've confirmed that EvaporateJS runs in a web worker. Anything related to the way webworkers process checksums can be in a new ticket, as needed. Thanks again @m-andrew-albright .

**Closed by bikeath1337** 2017-05-05 10:44 UTC

**Comment by m-andrew-albright** [comment] 2017-05-05 12:09
No problem, thanks for all the work you do in evaporate, and thanks for
taking the time to help us solve our problem!

**Comment by bikeath1337** [comment] 2017-10-13 13:23
@YMIndustries @m-andrew-albright https://github.com/TTLabs/EvaporateJS/pull/385 tries to address the non-cooperative nature of the checksum calculation. Would you like to see if it works?

https://github.com/TTLabs/EvaporateJS/pull/385

**Comment by YMIndustries** [comment] 2017-10-16 22:43
@bikeath1337 I actually can't reproduce the issue on Chrome v61.0.3163.100 with Evaporate v2.0.9. It never occurred in Firefox, maybe it was a Chrome bug that's now fixed?
